### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by modulexcite** [sindresorhus/gulp-app#27] opened 2016-08-16 20:19 UTC
is this going to be released for the Windows platform? @sindresorhus you're a programming god and you rock, thanks for all the awesome work you do and share with the rest of us.

**Comment by sindresorhus** [comment] 2016-08-16 20:42
Yes, that was the plan all along, but I just haven't had enough time, even working full-time on open source... Maybe in a month.

**Comment by modulexcite** [comment] 2016-08-17 00:00
great, look forward to it. thanks.

**Comment by sindresorhus** [comment] 2019-01-04 21:20
Duplicate of #1

**Closed by sindresorhus** 2019-01-04 21:20 UTC
